export const GET_BRANDS = "GET_BRANDS"
export const GET_BRANDS_SUCCESS = "GET_BRANDS_SUCCESS"
export const GET_BRANDS_FAILUE = "GET_BRANDS_FAILUE"

export const GET_BRAND_DETAILS = "GET_BRAND_DETAILS"
export const GET_BRAND_DETAILS_SUCCESS = "GET_BRAND_DETAILS_SUCCESS"
export const GET_BRAND_DETAILS_FAILURE = "GET_BRAND_DETAILS_FAILURE"
