export const GET_CHOCOLATES = "GET_CHOCOLATES"
export const GET_CHOCOLATES_SUCCESS = "GET_CHOCOLATES_SUCCESS"
export const GET_CHOCOLATES_FAILURE = "GET_CHOCOLATES_FAILURE"

export const GET_CHOCOLATE_DETAILS = "GET_CHOCOLATE_DETAILS"
export const GET_CHOCOLATE_DETAILS_SUCCESS = "GET_CHOCOLATE_DETAILS_SUCCESS"
export const GET_CHOCOLATE_DETAILS_FAILURE = "GET_CHOCOLATE_DETAILS_FAILURE"

